"""add_email_source_configs

Revision ID: 527c5c2072df
Revises: b1f4e7a2c901
Create Date: 2026-05-24 22:08:54.274471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '527c5c2072df'
down_revision: Union[str, None] = 'b1f4e7a2c901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_source_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('sender_pattern', sa.String(length=255), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sender_pattern', name='uq_user_sender_pattern')
    )
    op.create_index(op.f('ix_email_source_configs_id'), 'email_source_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_source_configs_id'), table_name='email_source_configs')
    op.drop_table('email_source_configs')
    # ### end Alembic commands ###
