"""add_payment_source

Revision ID: 628c6541bc23
Revises: 7a9eaedc9937
Create Date: 2026-04-05 14:20:32.980397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '628c6541bc23'
down_revision: Union[str, None] = '7a9eaedc9937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payment_source', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'payment_source')
    # ### end Alembic commands ###
